Set pack version to 3
Chisel-Team/CTM-Resources pull request #6
Opened 2018-07-23 00:13 UTC by gudenau

2018-07-23 22:16 UTC, InsomniaKitten commented on pack.mcmeta
> +    "pack_format": 3,
This change will break `soulshardstow/blockstates/BlockCage` and `enderio/blockstates/blockIngotStorage`

2018-07-23 22:19 UTC, ChloeDawn requested changes

2018-07-23 22:19 UTC, InsomniaKitten commented on pack.mcmeta
> +    "pack_format": 3,
Pack format 3 enforces lower-casing, and CTP has non-lower-case files. This change will break `soulshardstow/blockstates/BlockCage` and `enderio/blockstates/blockIngotStorage`

2018-07-23 23:33 UTC, Drullkus requested changes
Unfortunately I’d like to keep this version of the pack on the repo compatible with 1.10, and then pack to 1.12.2 editions locally for Curseforge.

2018-07-24 00:44 UTC, closed without merging

2018-07-24 02:19 UTC, gudenau commented
Alrighty.